### ISSUE TITLE
Upgrade graph API

### ISSUE THREAD

**Issue by rthallisey** [operator-framework/operator-lifecycle-manager#1040]
## Feature Request
As a operator developer that's had many operator releases, I would like capture what my upgrade DAG (Directed Acyclic Graph) looks like because it's hard for me to visualize it from all the releases I've had.  It would be nice for OLM to expose an API, so I can do a POST request with the name of a CSV that OLM is aware of and OLM returns to me a payload with the DAG.

**Comment by TriTiger** [comment]
a operator developer that's had many operator releases, I would like capture what my upgrade DAG (Directed Acyclic Graph) looks like because it's hard for me to visualize it from all the releases I've had. It would be nice for OLM to expose an API, so I can do a POST request with the name of a CSV that OLM is aware of and OLM returns to me a payload with the DAG.
