### ISSUE TITLE
configuration enforcement on available operator

### ISSUE THREAD

**Issue by sa-cloud** [operator-framework/operator-lifecycle-manager#1143]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

best practice

## Question

Hi,
we have a use-case, where we want to use an opensource operator, available on operator hub, as a complementary to our product.
In case this operator (it's custom resource instance) is intended to be used with our product, we want to impose some configuration values.
If in the general installation case of this operator, the user is suggested to configure 20 parameters in the OLM, in our scenario, we want to supply a fixed set of values.
We only want the user to supply 3-4 required configuration parameter values, and we want to supply the rest of parameters, say in a separate yaml, to be passed to the custom resource seamlessly.
Is there a recommended pattern to do such configuration enforcement on available operators?

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

  

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by Denton24646** [comment]
Hi, thanks for your question. This is a great use case and here is the simplest, best way to approach this issue: 

Write a simple operator that has a chart inside it (potentially via the helm-app-operator via the operator SDK)- its configured to watch a particular CRD type, and any time it sees an instance of the CRD type, it can stamp out a instance of the CR that you are interested in but provide the user to specify additional fields on the spec. This enables defaulting because you can provide the default values in the `values.yaml` file. This seems like a lot but if you look at the operator-sdk you can build a helm operator in a single command with your chart provided. 
https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/user-guide.md.

For example, using the Couchbase Operator
Step 1) Write a small operator (using the helm operator pattern in the sdk) that has a chart in it that has an instance of the `CouchbaseCluster` CR, with templating for the values that you would like the user to define. 

Step 2) Define your own MyCouchbase CRD, and every instance of that CR results in a Couchbase CR, because the instance spec is entirely defined by the values.yaml file in the operator.  

It may look a little confusing but all the steps are here https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/user-guide.md

**Comment by sa-cloud** [comment]
Hi, as I wrote, we want to use a ready operator, but only want to supply our configuration. We are trying to avoid creating our own operator, not because we don't know how, but because we would not wan't to split away. 
I see examples of operators that have multiple crds inside.

**Comment by Denton24646** [comment]
Another approach would be to setup an [admission webhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/) that modifies the values in the CR after creation to your desired values. Adding something like [Open Policy Agent](https://www.openpolicyagent.org/docs/latest/) can take this to the next level of complexity. 

You're right though in that this is not a direct use-case of OLM, although it would be interesting to incorporate this behavior. Fine-grained tuning of operators and their operands installed in the cluster via OLM would be an interesting project to explore
