### ISSUE TITLE
Cannot delete operator after delete subscription

### ISSUE THREAD

**Issue by clyang82** [operator-framework/operator-lifecycle-manager#1168]
From the [document](https://docs.openshift.com/container-platform/4.2/operators/olm-deleting-operators-from-cluster.html), you can see that:

> To delete, or uninstall, an Operator from your cluster, you can simply delete the Subscription to remove it from the subscribed namespace. If you want a clean slate, you can also remove the Operator’s ClusterServiceVersion (CSV) and Deployment.

In my environment, the `operator` cannot be delete after deleted `subscription` successfully.
Here is logs of `catalog-operator-xxx`
```
time="2019-12-04T03:21:58Z" level=info msg=syncing event=delete reconciling="*v1alpha1.Subscription" selflink=/apis/operators.coreos.com/v1alpha1/namespaces/openshift-operators/subscriptions/my-operator-subsription
E1204 03:21:58.142729       1 reconciler.go:246] unexpected subscription state in installplan reconciler *subscription.subscriptionDeletedState
```
There is no any `InstallPlan` in my environment
```
chunlins-mbp:memcached-operator clyang$ oc get ip --all-namespaces
No resources found.
chunlins-mbp:memcached-operator clyang$ oc get pod
NAME                                  READY   STATUS    RESTARTS   AGE
example-memcached-0.0.2-pod           1/1     Running   3          30h
example-memcached-pod                 1/1     Running   30         30h
memcached-operator-84d559f89d-k9hnh   1/1     Running   0          8h
```

I am using the openshift 4.2 embedded olm 0.11 . Is it fixed in the latest version?

**Comment by gyliu513** [comment]
I also encounter the same issue and I was using olm 0.13.0 .

**Comment by njhale** [comment]
This is expected behavior. Deleting a `Subscription` should not delete the operator it installed. The wording in that document is incorrect. Further down, it explains that [deleting an operator also requires the manual deletion of the CSV](https://docs.openshift.com/container-platform/4.2/operators/olm-deleting-operators-from-cluster.html#olm-deleting-operator-from-a-cluster-using-cli_olm-deleting-operators-from-a-cluster).

I'm going to notify a member of the OpenShift docs team and close this issue once we have it tracked on that side.

@adellape how do we go about getting these docs amended?

**Comment by clyang82** [comment]
@njhale Thanks for your confirmation that delete an operator requires the manual deletion of the CSV.

**Comment by adellape** [comment]
@njhale Thanks, opened https://github.com/openshift/openshift-docs/pull/18632 to address.
