### ISSUE TITLE
Does OLM support downgrade

### ISSUE THREAD

**Issue by clyang82** [operator-framework/operator-lifecycle-manager#1177]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

> 
OLM extends Kubernetes to provide a declarative way to install, manage, and **upgrade operators** and their dependencies in a cluster.

There is not mentioned that OLM downgrade support. I just wonder to know if we support downgrade or not. 

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

When I use helm to upgrade, I can use helm downgrade to rollback the previous version. But from the document and my testing, I did not find the way how to download by OLM.

**Comment by clyang82** [comment]
@camilamacedo86 @dinhxuanvu I saw there is a document mentioned that the downgrade - https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/dependency-resolution.md#dependency-resolution

Could you please elaborate more details? Thanks.

FYI @gyliu513

**Comment by jpeeler** [comment]
The downgrade that has been mentioned in that document is referring more to an attempted upgrade that is reverting, rather than explicitly supporting an arbitrary downgrade. Philosophically, OLM is designed to always upgrade to the next version. If an emergency fix is needed, that fix should be made in a new CSV to be made available to OLM.

**Comment by clyang82** [comment]
@jpeeler Thanks for you reply. If we want to rollback the previous version(I do not like this new version), there is no way by using olm. You have to reinstall.

**Comment by wei-lee** [comment]
I am interested in this topic as well and I would like to know what prevents OLM from support downgrading. Yes, it's possible to do downgrade by rolling forward, however, I think that's a hack and not a proper solution.

**Comment by dinhxuanvu** [comment]
At the moment, OLM doesn't support downgrading but we are looking into the feature. However, there isn't a concrete plan for it yet. At the moment, downgrading is just another from of upgrading as far as OLM is concerned.

There are a few issues that OLM needs to resolve in order to enable downgrading. One of them is CRD and its CR handling. As you know, OLM is managing the CRD but not the CR created from the API provided by CRD. In order to downgrade and ensure no data loss, OLM needs to handle the CR migration before it can downgrade a CRD (if there are changes between this version of CRD and the prior one). Plus, if there are another operator depending on a specific API/CRD that this operator owns, then downgrading can potentially break those operators if there are incompatible changes in previous version. That situation needs to be handled as well. Furthermore, depending on when the downgrading happens, it may not even be possible if previous version is no longer applicable anymore due to cluster/k8s version upgrade and some k8s APIs have been deprecated.

This is an interesting feature that can be very helpful but there isn't an immediate plan for it right now.

**Comment by dinhxuanvu** [comment]
@mhtgrwl5 As far as I know, OLM doesn't have any plans on rollback feature. However, you can ask questions on this on #olm-dev on Kubernetes slack channel.

**Comment by mhtgrwl5** [comment]
@dinhxuanvu Thanks. I will investigate it further.

**Comment by Stefanqn** [comment]
any news on this topic? I just had the case were keycloak updated to an incompatible version of our keycloak plugin. Having an option to downgrade/revert or just force a specific version would be useful.

**Comment by ShadiAlbatal** [comment]
Maybe you could add a new parameter on each install plan that if set to true, will redeploy. cos I can still see earlier install plans
