### ISSUE TITLE
After operator uninstall, operator group remains.

### ISSUE THREAD

**Issue by horis233** [operator-framework/operator-lifecycle-manager#1262]
## Type of question

What is the best practice to uninstall the Operator? (from CLI and console)
Why the operator group is not deleted?

## Question

**What did you do?**

I follow this instruction to delete the installed operator.
Could you tell me why the operator group is not deleted?

**What did you expect to see?**

The operator group is deleted as well.

**Environment**
* operator-lifecycle-manager version:
OCP 4.2

* Kubernetes cluster kind: 
Openshift

**Comment by exdx** [comment]
Hi @horis233, 

This is expected behavior - we keep the operator group around even after the operator is deleted because the operator group represents configuration between operators and namespace(s) and can be used again. For example if you were to then reinstall the operator, it would work. 

It's similar to how namespaces work - if you remove all the pods from a namespace, the namespace continues to exist. operator groups are OLM's way of tying operators to namespaces so it has similar semantics.

**Comment by horis233** [comment]
@exdx 
Thanks for your explanation! It is very clear to me.
