### ISSUE TITLE
When delete CSV and subscription, how to make operator waiting for its CR deleted

### ISSUE THREAD

**Issue by horis233** [operator-framework/operator-lifecycle-manager#1302]
## Question

**What did you do?**
When I delete an operator by the Openshift operator hub or delete it subscription and CSV directly, all the CRs from this operator are removed. Because the operator is removed, there is no logic handling uninstall, the resource generated by the operator left in the cluster. 

I want to ask if there is a way when deleting the CSV to make the operator waiting for all its CR removed first then remove the operator. In this case, the resource generated by the operator could be clean up.   

I have considered setting the CR as the `owner` of all the generated resources, but some resources are not in the same namespace as the CR.
  
**What did you expect to see?**
When deleting the operator on the Openshift console.

The operator has a finalizer to wait CR removed first, then delete the operator deployment. 

**What did you see instead? Under which circumstances?**
When deleting the operator on the Openshift console.

Operator and CR are removed before they lost their owner, but the generated resource left in the cluster.

**Environment**
* operator-lifecycle-manager version:
0.13.0

* Kubernetes version information:  
kubernetes v1.16.2

* Kubernetes cluster kind: 
Openshift

**Comment by njhale** [comment]
Hi @horis233, thanks for posting!

> When I delete an operator by the Openshift operator hub or delete it subscription and CSV directly, all the CRs from this operator are removed.

OLM does not actively delete the CRDs or CRs of an operator when its `Subscription` or `CSV` are deleted. One possible reason for the behavior you're observing could be that the operator creates `OwnerReferences` on the resources it manages to its own Deployment. We would need to check out the operator to be sure. 

I know the OpenShift UI gives extra delete options which may be the source of the problem as well. Look for a checkbox the next time you attempt to delete an operator.

> Because the operator is removed, there is no logic handling uninstall, the resource generated by the operator left in the cluster.

I think there could be value in an uninstall hook, but I'm curious how far the `PreStop` [container lifecycle hook](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks) can get us.

> I want to ask if there is a way when deleting the CSV to make the operator waiting for all its CR removed first then remove the operator. In this case, the resource generated by the operator could be clean up.

Finalizers can be tricky in situations like this. If added, it would need to be optional since I don't think deleting operator's state is the desirable default. There's also the question of signaling OLM to determine if the cleanup is complete. Definitely something to think about, but I think a first-class uninstall hook may be more useful.

**Comment by horis233** [comment]
@njhale 
Thanks, Nick for your quick response. 

Your explanation is very clear and useful for me.

From my understanding, An Operator is like an installer. Users can use it to install an application. If users want to delete the application, they need to use the installer to delete it instead of deleting the installer.
Operators are also like this. So it makes sense that the generated resources are left in the cluster after the CSV is deleted manually or by OCP console. 

Moreover, I found in OCP 4.3, when I want to delete an operator, it shows 
```
This will remove the operator from default. Your application will keep running, but it will no longer receive updates or configuration changes.
```
<img width="1306" alt="Screen Shot 2020-02-19 at 10 41 32 PM" src="https://user-images.githubusercontent.com/33276414/74899587-57ed5880-536b-11ea-82ed-ca1348352137.png">
