### ISSUE TITLE
Support for multinamespace installMode, is this going to be deprecated?

### ISSUE THREAD

**Issue by huizengaJoe** [operator-framework/operator-lifecycle-manager#1305]
I am looking for guidance on the usage of the multinamespace installmode, I thought that I heard awhile ago that using this mode was discouraged and perhaps going to be deprecated.  I have teams that are starting development on new operators and they are being directed to make sure they develop and test all 4 installModes, if this is going away I would like to be able to convey that message to these teams.

Any details you can provide on this topic would be greatly appreciated!

I have been doing some initial testing thru the OCP OperatorHub UI and I am not seeing a way to even specify this mode when creating a subscription

**Comment by awgreene** [comment]
Hello @huizengaJoe - AFAIK there are no plans to deprecate this feature yet but we typically encourage operator authors not to use this feature because it has proven to be a difficult concept for users to understand.

**Comment by awgreene** [comment]
There is also a lack of support for multiple instances of operators that introduce an APIServices, this same issue will appear when OLM supports [Conversion Webhooks](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/).

**Comment by huizengaJoe** [comment]
Hi @awgreene thanks for the quick reply, can u elaborate a bit more on your last comment?  I assume you are referring to the apiservicedefintions  spec element in the CSV,  I am not sure how or when to use these,  if you can point me to any docs or examples that would be great.  Also just want to clarify, your comment about 'support for for multiple instances" are you saying that this a problem with the multinamespace installmode or even with namespace scoped operators where I have the same operator installed more that once?

**Comment by giacomoch** [comment]
@awgreene thanks for the replies. We are currently developing our operator and struggling with multinamespace support, which is on our roadmap. Our current blocker is getting the operator to create the correct ServiceAccounts on all namespaces in it's scope, but Im sure we will hit other blockers to get our Operator and Application working.

Is the current guidance from RedHat to not work towards supporting multi-namespace? Will it be supported? Or will all these bugs/support questions be resolved in the foreseeable future?

**Comment by awgreene** [comment]
Hello @huizengaJoe,

> Hi @awgreene thanks for the quick reply, can u elaborate a bit more on your last comment? I assume you are referring to the apiservicedefintions spec element in the CSV, I am not sure how or when to use these, if you can point me to any docs or examples that would be great. 

The apiservicedefinitions spec is used by operators that implement an [APIService](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/) to extend the Kubernetes API. The following bullet-points, taken from [apiservice-builder](https://github.com/kubernetes-sigs/apiserver-builder-alpha), highlights why you may want to use an API Service over a CRD to extend k8s:

- Makes your apiserver adopt different storage APIs rather than ETCDv3
- Extends long-running subresources/endpoints like websocket for your own resources
- Integrates your apiserver with whatever other external systems 

>Also just want to clarify, your comment about 'support for for multiple instances" are you saying that this a problem with the multinamespace installmode or even with namespace scoped operators where I have the same operator installed more that once?

It isn't necessarily a problem - I was just highlighting that if an operator provides clusterscoped resources such as an APIService multiple installations may behave differently than users expect. For example, an APIService is only installed once on the cluster because it is a clusterscoped resource that handles Kube API requests against a GroupVersion.

**Comment by flickerfly** [comment]
Am I correctly understanding that building operators that act at a cluster scope across a global OperatorGroup is discouraged only in scenarios where there may be more than one of these operators running?

**Comment by dinhxuanvu** [comment]
This issue is stale. Closed. Please feel free to reopen if needed.
