### ISSUE TITLE
Docs: Clarification opportunities in the Architecture document

### ISSUE THREAD

**Issue by flickerfly** [operator-framework/operator-lifecycle-manager#1346]
Now that I've been working with OLM for a bit and have wrapped my head around the basics, I came away from reading the [architecture document](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/architecture.md) with a few points of confusion and even some places where it seems like the document is contradicting itself. It would be great if the doc could be updated to clarify these and I'd just generally like to know better.

I hope this format is useful. I'd be glad to attempt a reword if I can get an appropriate understanding.

**What about PackageManifests?**
The first and second table in the Architecture document do not include the PackageManifest resources. Why? 

**What about the Package Server stuff?** 
The role of the 'Package Server' pods isn't discussed. How is it involved? Perhaps the 'Catalog (Registry) Design' section is related to this? 

**How does an InstallPlan actually get implemented?**
After reading through, I'm unclear who is responsible for what when resolving the InstallPlan. Is the Catalog Operator going to create resources in some instances and if that doesn't happen, then the OLM Operator will create them in other instances? 

I read this quote which leads me to believe that Catalog Operator creates all the resources for an operator to function.
"Once approved, _the Catalog Operator will create all of the resources in an InstallPlan_; this should then independently satisfy the OLM Operator, which will proceed to install the ClusterServiceVersions." 

However, the table at the top of the document says the OLM operator creates the Roles, RoleBindings ServiceAccounts and Deployments. Also, earlier in the document it says "OLM is responsible for installing applications." I'm assuming applications means operators specifically and the parts required for them to run. Additionally, the ClusterServiceVersion is identified at the top as being created by the Catalog Operator, not OLM Operator.

**Comment by ecordell** [comment]
Great questions @flickerfly 

I will answer here, but let's leave this issue open until we can persist it into the docs.

> What about PackageManifests?
> The first and second table in the Architecture document do not include the PackageManifest resources. Why?

PackageManifests and the package server are really an additional / optional layer on top of OLM. It's a vaneer API to make it easy to query the underlying CatalogSources.

They should still be documented, but that's why they're not prominent in the docs.

> What about the Package Server stuff?
> The role of the 'Package Server' pods isn't discussed. How is it involved? Perhaps the 'Catalog (Registry) Design' section is related to this?

The package server pods are what translate kubectl commands to CatalogSource grpc queries. We should flesh out this section as well.

> How does an InstallPlan actually get implemented?
> After reading through, I'm unclear who is responsible for what when resolving the InstallPlan. Is the Catalog Operator going to create resources in some instances and if that doesn't happen, then the OLM Operator will create them in other instances?

This is confusing largely because we changed how this worked at one point.

Originally, creating a CSV would also create the serviceaccount/rbac for the operator. InstallPlans would create CRDs + CSVs only. 

Currently, InstallPlans generate "the set of things a CSV says it requires to run" which includes rbac and serviceaccounts. When that change happened, responsibility moved from the olm operator (managing csvs) to the catalog operator (managing installplans).

The analogy here is roughly:

 catalog operator = high level user interface (think yum or apt)
 olm operator = low level interface (think rpm or dpkg)

The change of responsibility for service account creation was to make it reasonable to hand out permission to create ClusterServiceVersions. 

I hope that helps clarify a bit, and thank you for pointing out that we forgot to update a few things in that doc.

**Comment by flickerfly** [comment]
Thanks for this answer and the one on my mailing list post. That added some additional illumination so I'm going to copy it on over here and I think I'll take a stab at updating that document. 

> The package server is an apiserver that provides a "veneer" over the backing catalogsources.
>
>OLM queries catalogsources over a grpc api that is not very friendly to non-machine users. The packageserver connects over that same api and exposes the contents of the catalogs via a normal kube api (PackageManifests), so that you can browse what's available just with oc or kubectl (or the openshift console).
>
>It's important for the openshift console experience and for discovering the contents of catalogs, but it's not important to the function of OLM itself. If you know ahead of time what package/channel you want, you can create a Subscription with those values and everything will work as expected, even if the packageserver was never installed on the cluster.
