### ISSUE TITLE
Operator upgrades using the same channel failing

### ISSUE THREAD

**Issue by huizengaJoe** [operator-framework/operator-lifecycle-manager#1347]
I have a ocp 4.4 nightly from 3/2/2020, I am trying to test out using olm to automatically update my operator to a new z level ie going from 0.0.3 to 0.0.4 to 0.0.5.  In my example I have not changed the CRD between versions, i just created a new CSV that now `replaces` my old version.  I am using operator-sdk 0.15.2 with opm.  I built my 3 operator bundles

https://quay.io/repository/huizenga/app-operator-bundle:0.0.3,0.0.4 and 0.0.5

I used opm to built 3 separate index images
```
opm index add -c docker --bundles quay.io/huizenga/app-operator-bundle:0.0.3  --tag quay.io/huizenga/app-operator-index:0.0.3
```
```
opm index add -c docker --bundles quay.io/huizenga/app-operator-bundle:0.0.3,quay.io/huizenga/app-operator-bundle:0.0.4  --tag quay.io/huizenga/app-operator-index:0.0.4
```

```
opm index add -c docker --bundles quay.io/huizenga/app-operator-bundle:0.0.3,quay.io/huizenga/app-operator-bundle:0.0.4,quay.io/huizenga/app-operator-bundle:0.0.5  --tag quay.io/huizenga/app-operator-index:0.0.5
```
For my last attempt, I created my catalogsource pointing to  quay.io/huizenga/app-operator-index:0.0.4
I then created a subscription which deployed eveything as I would have expected (ie version 0.0.4 of my app-operator got deployed)

I then updated my catalogsource to point to quay.io/huizenga/app-operator-index:0.0.5, the new registry pod started up, olm detected that there was a new version of my operator (0.0.5) in the alpha channel and proceeded to try to upgrade my operator.  The update fails, wonder what I am doing wrong.

Here is the installplan output for the update:
```
apiVersion: operators.coreos.com/v1alpha1
kind: InstallPlan
metadata:
  generateName: install-
  selfLink: >-
    /apis/operators.coreos.com/v1alpha1/namespaces/joeolm/installplans/install-szj4r
  resourceVersion: '173620'
  name: install-szj4r
  uid: e24a9a21-a2da-474c-aa8d-753021b4138c
  creationTimestamp: '2020-03-03T21:47:04Z'
  generation: 1
  namespace: joeolm
  ownerReferences:
    - apiVersion: operators.coreos.com/v1alpha1
      blockOwnerDeletion: false
      controller: false
      kind: Subscription
      name: app-operator
      uid: 3cad4bb4-d61a-4ca6-8834-3475e77e2453
spec:
  approval: Automatic
  approved: true
  clusterServiceVersionNames: []
status:
  catalogSources: []
  conditions:
    - lastTransitionTime: '2020-03-03T21:47:11Z'
      lastUpdateTime: '2020-03-03T21:47:11Z'
      message: >-
        pre-existing CRD owners found for owned CRD(s) of dependent CSV
        app-operator.v0.0.5
      reason: InstallComponentFailed
      status: 'False'
      type: Installed
  phase: Failed
```

**Comment by ecordell** [comment]
Did anything modify the installplan? Is that the entirety of the installplan or did you shorten it for display?

This line: 

```yaml
  clusterServiceVersionNames: []
```

is suspicious - OLM populates this list on `Create` of the InstallPlan, and adds the full contents of the CSV to the status. It's that list that is checked when producing the error message you're seeing.

(As a side note - this error in general shouldn't be possible to hit; the latest resolver considers all owned apis in the namespace during resolution and can't produce a set that would hit a "pre-existing owner" - so we can remove this from OLM entirely)

**Comment by huizengaJoe** [comment]
here are the 2 installplans, 
  `clusterServiceVersionNames: []` is empty in both 

[installplanSuccess-v0.0.4.txt](https://github.com/operator-framework/operator-lifecycle-manager/files/4287375/installplanSuccess-v0.0.4.txt)
[installplanFail-v0.0.5.txt](https://github.com/operator-framework/operator-lifecycle-manager/files/4287376/installplanFail-v0.0.5.txt)

**Comment by huizengaJoe** [comment]
I tried the same thing on an OCP 4.3 cluster and the upgrade worked fine
[installplan-43cluster-updated-sucessfully.txt](https://github.com/operator-framework/operator-lifecycle-manager/files/4287678/installplan-43cluster-updated-sucessfully.txt)

**Comment by fantapsody** [comment]
Hello @ecordell @huizengaJoe ,

I may have encountered a similar problem: got  a "pre-existing CRD owners found for owned CRD(s) of dependent CSV..." error while trying to upgrade privated built operator bundle with OLM using a self-built index image as the catalog source
- the operator was created using operator-sdk
- the csv was generated with operator-sdk generate csv
- the index image was built with opm index add
- the olm version is 0.14.1

I tried to read the source code of OLM and debugged the catalog-operator in a minikube cluster, it seems the name of the csv is not added to `clusterServiceVersionNames` in `InstallPlanSpec` if it is loaded from the bundle, :
https://github.com/operator-framework/operator-lifecycle-manager/blob/8985872bfd5888c8d7d49e4dfc9be162a87691e7/pkg/controller/registry/resolver/resolver.go#L111
https://github.com/operator-framework/operator-lifecycle-manager/blob/8985872bfd5888c8d7d49e4dfc9be162a87691e7/pkg/controller/operators/catalog/operator.go#L1020

I modified the code to add the name of unpacked CSV to `InstallPlanSpec.ClusterServiceVersionNames` and deployed it in a test cluster, it seems the operator update went well then. Could you confirm that wether the mentioned behaviour is a bug or by design? Thanks! @ecordell

**Comment by ecordell** [comment]
@fantapsody thanks for hunting this down; it's definitely a bug.

**Comment by dinhxuanvu** [comment]
This issue is stale. Closed. Please feel free to reopen if needed.
