### ISSUE TITLE
Broken link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by matskiv** [operator-framework/operator-lifecycle-manager#1628]
## Bug Report
A link to `short document on reporting bugs` in CONTRIBUTING.md is broken.
It links to `/doc/dev/reporting_bugs.md` file, which doesn't exist.

**Comment by timflannagan** [comment]
This appears to have been resolved since this had been opened and the link resolves for me. Poking around the git history for this files/directories didn't indicate much had changed since the introduction of those files.

https://github.com/operator-framework/operator-lifecycle-manager/blob/master/CONTRIBUTING.md#reporting-bugs-and-creating-issues looks like it correct links to https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/dev/reporting_bugs.md.
