### ISSUE TITLE
Release 0.14.2 missing assets

### ISSUE THREAD

**Issue by ricfeatherstone** [operator-framework/operator-lifecycle-manager#1646]
## Bug Report

There are no published assets for release 0.14.2 so unable to work with olm using the operator-sdk in crc 1.12 

**What did you do?**

```
$ operator-sdk olm status --olm-namespace openshift-operator-lifecycle-manager
I0717 13:30:17.665286   29594 request.go:621] Throttling request took 1.038091078s, request: GET:https://api.crc.testing:6443/apis/storage.k8s.io/v1beta1?timeout=32s
INFO[0002] Fetching CRDs for version "0.14.2"           
FATA[0002] Failed to get OLM status: failed to get resources: failed to fetch CRDs: request failed: failed GET 'https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.14.2/crds.yaml': unexpected status code 404, expected 200: Not Found 
````

**Comment by robherley** [comment]
Anyone have a fix or workaround for this?

**Comment by timflannagan** [comment]
Interesting - it looks like we dropping the ball there with that release. I wasn't able to find any explicit v0.14.2 release, but I did find a v0.14.2 release tag, and as reported here, it didn't contain the relevant assets needed to install OLM, so that helps explain that failure when running the SDK. In any case, the 0.14.x release isn't supported anymore, so I'm going to close this out as users can upgrade to a newer minor version release that has the release artifacts properly generated.
