### ISSUE TITLE
Evicted CatalogSource pod causes failure

### ISSUE THREAD

**Issue by flickerfly** [operator-framework/operator-lifecycle-manager#1677]
## Bug Report

**What did you do?**
A grpc catalog pod setup by CatalogSource was evicted by the cluster. 

**What did you expect to see?**
A new pod based on the catalog container image would be deployed.

**What did you see instead? Under which circumstances?**
A new pod did not get deployed until I deleted the evicted pod. Then it immediately deployed a new pod.

**Environment**
OLM 0.12.0 on OpenShift 3.11

$ oc version
oc v3.11.157
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://awnsercics01.esg.nswc.navy.mil:8443
openshift v3.11.157
kubernetes v1.11.0+d4cacc0

**Additional context**
I'm not sure how to replicate this issue and am not in a place where I can upgrade OLM. I'm hoping this is a quick "oh we forgot to include that" type thing. If not, I'm comfortable with it simply being closed as WONTFIX. It isn't to a point where it is worth major effort.

**Comment by kramvan1** [comment]
I believe this is because of the open toleration:
```
tolerations:
      - operator: Exists
```
Which matches any node, but does not account for nodes that are not schedulable or pods that have been evicted.

I see no reason to have this toleration for the catalog source pod, there's no specific use case for it.     
I will put up a PR to remove this.
