### ISSUE TITLE
Origin Console: http: proxy error: dial tcp 127.0.0.1:59041: connect: connection refused

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-lifecycle-manager#1825]
## Bug Report

We cannot access the web console `http://localhost:9000` from the browser as the local process launched reports the following error

```
make run-console-local
Running script to run the OLM console locally:
. ./scripts/run_console_local.sh
latest: Pulling from openshift/origin-console
77c58f19bd6e: Pull complete
47db82df7f3f: Pull complete
9e518d0279d9: Pull complete
b4070df4e3cc: Pull complete
fd62ead4f60f: Pull complete
Digest: sha256:a6101e43ea6d2bee2dc2f320ffd8e3af1305815fd730575f1d6b3bdc39665c14
Status: Downloaded newer image for quay.io/openshift/origin-console:latest
quay.io/openshift/origin-console:latest
Using https://127.0.0.1:59041
The OLM is accessible via web console at:
http://localhost:9000/
Press Ctrl-C to quit
2020-10-22T13:14:36Z http: proxy error: dial tcp 127.0.0.1:59041: connect: connection refused
```
I can curl to the server even if I cannot get the resources using as `user : system:anonymous`
```
curl -k https://127.0.0.1:59041
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {

  },
  "code": 403
}%
```

### Information

- Kubernetes cluster type: kind
- Kubernetes version: 1.19
- OLM version: latest

**Comment by kevinrizza** [comment]
This seems like it is an issue with the latest version of the openshift console image? That's a separate project -- https://github.com/openshift/console. Seems like you could use a tagged release of their image instead of the latest tag used in the script referenced by the makefile for now? https://github.com/operator-framework/operator-lifecycle-manager/blob/master/scripts/run_console_local.sh#L41

Either way, I don't think this is something this project can fix for now, and filing an issue on the console project would provide more help.

**Comment by cmoulliard** [comment]
I fixed the problem. This is documented here : 
https://github.com/openshift/console/issues/6982#issuecomment-714906668

**REMARK**: If you want to run the console deployed on k8s instead of docker, dont hesitate to use the resources I shared within the ticket fixing the issue ;-)
