### ISSUE TITLE
Support kinds: Service, NetworkPolicy in CSV

### ISSUE THREAD

**Issue by saada** [operator-framework/operator-lifecycle-manager#1858]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have an operator that I would like to add to OperatorHub. OLM CSV allows deployments and RBAC permissions, but no clear way to setup other kinds such as Service and NetworkPolicy. We need these kinds because the operator has multiple CRDs and deployments that talk to each other over the network.

**Describe the solution you'd like**
Is it possible to add support for other kinds? Maybe add a `CSV.spec.services` and a `CSV.spec.networkpolicies`? OR support plain YAML manifests with those resources?

**Comment by exdx** [comment]
Hi @saada, 

OLM supports adding services to the operator bundle as plain yaml manifests. OLM will install the service in the same namespace as the operator when installing the bundle. There's no need to reference the service in the CSV explicitly  👍

**Comment by saada** [comment]
@exdx , I'm running into errors when running 

`operator-sdk bundle validate --select-optional=operatorhub . --verbose`

```
ERRO[0000] Error: Value networking.k8s.io/v1, Kind=NetworkPolicy: unsupported media type registry+v1 for bundle object 
```

Is there a different media type I should be using?

**Comment by exdx** [comment]
@saada so we currently support `Service` type objects but not `NetworkPolicy` objects in the bundle. 

`NetworkPolicy` is an interesting resource because even though it's namespace scoped it could potentially affect other workloads in the cluster. We have added support for `PodDisruptionBudget` and `PriorityClass` types, which also can affect other workloads, but we were careful to provide additional documentation and validation for these objects. See

* https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/adding-pod-disruption-budgets.md
* https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/adding-priority-classes.md

So we could potentially add support for `NetworkPolicy` objects in the bundle but would have to go about it carefully. You could file an RFE at https://issues.redhat.com/projects/RFE/ (public) and we can prioritize it further from there.

**Comment by awgreene** [comment]
Closing this issue in favor of https://github.com/operator-framework/operator-lifecycle-manager/issues/1996.
