### ISSUE TITLE
Including potentially non-existing object's API types in bundle

### ISSUE THREAD

**Issue by miguelsorianod** [operator-framework/operator-lifecycle-manager#1860]
## Question

Hi,

As part of latest changes in operator-sdk (v1.2.0) now all generated objects are included in the `bundle/manifests` directory. This includes the Prometheus `ServiceMonitor` object when you enable it in `config/default/kustomization.yaml`.

Our operator optionally supports the generation of Prometheus-related objects conditionally to whether the Prometheus-related CRD objects are defined in the cluster.

When installing this bundle using OLM, if the cluster doesn't have the `ServiceMonitor` CRD API type (which is common on K8s native clusters), OLM fails at the InstallPlan installation step when trying to install the provided `ServiceMonitor` with a status of `UnsupportedResource`.

Is there a way to make OLM install the `ServiceMonitor` object only when the `ServiceMonitor` CRD definition exists on the cluster? This question is about `ServiceMonitor` object but it would really apply to all object Kinds that might not be defined in a cluster.

There's a little more context about this on the original issue I opened in the operator-sdk repository: https://github.com/operator-framework/operator-sdk/issues/4124

Thank you.

**Comment by exdx** [comment]
I think this is a reasonable feature request, but the risk is that by conditionally installing CRs (if the API is already present on the cluster) then in cases where the CR is intentionally not installed it could impact the performance of the operator. A `ServiceMonitor` object is an interesting case though because its not really core to the operator, and so conditionally installing it could make sense. 

Since the SDK is now by default placing a `ServiceMonitor` object in the bundle we may potentially have to support conditionally installing it so that the latest SDK operators and OLM work together on upstream clusters. 

> Our operator optionally supports the generation of Prometheus-related objects conditionally to whether the Prometheus-related CRD objects are defined in the cluster.

There is also the option of setting Prometheus as a [required CRD](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#required-crds) in your operator's CSV and therefore ensuring that those APIs are on cluster. Would require a hard dependency on prometheus though, which I think you're looking to avoid

**Comment by dinhxuanvu** [comment]
This issue is stale and will be tracked in #2375
