### ISSUE TITLE
The link ` extension apiservers ` is broken 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-lifecycle-manager#1924]
## Bug Report

**What did you do?**
Click on ` extension apiservers ` in https://olm.operatorframework.io/docs/tasks/packaging-an-operator/: 

<img width="740" alt="Screen Shot 2020-12-23 at 11 53 06" src="https://user-images.githubusercontent.com/7708031/102993644-74bb6500-4515-11eb-860a-4bf1572ccb24.png">

**What did you expect to see?**
The link works and redirects me to the doc

**What did you see instead? Under which circumstances?**
Go to the same page on the top

**Comment by timflannagan** [comment]
Closing this out as (almost all) documentation is now housed in the o-f/olm-docs repository. The current link has since removed the link entirely and just contains a TODO comment about documenting that example: https://olm.operatorframework.io/docs/tasks/creating-operator-manifests/#extension-apiservers-and-apiservices. Likely worth opening an issue against that repository to remove that TODO comment entirely.
