### ISSUE TITLE
imagePullSecrets not available in yaml manifest

### ISSUE THREAD

**Issue by apurvabhandari** [operator-framework/operator-lifecycle-manager#2084]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).
I have my cluster in private subnet and don't have access to internet to pull the images. I have added `imagePullSecrets` to other deployment (i.e. olm-operator, catalog-operator) and it is working fine. But for kind CatalogSource it is not working.

**What did you expect to see?**
I am expecting the last two lines that will take as a imagePullSecrets
```apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: quay.io/operatorhubio/catalog:latest
  displayName: Community Operators
  publisher: OperatorHub.io
  imagePullSecrets:
  - name: mysecret 
 ```
**What did you see instead? Under which circumstances?**
If I use this, then cluster is able to pull images from my private repository with secret mysecret.

**Environment**
* operator-lifecycle-manager version:
v0.17.0

* Kubernetes version information:
1.18.9

* Kubernetes cluster kind: 

**Possible Solution**
imagePullSecrets needs to be added where the images are being pulled. This will help in private subnet clusters.

**Comment by exdx** [comment]
Hi @apurvabhandari , the field on the catalog source spec is called `secrets` not `imagePullSecrets`. I think if you were to change it, and provide the name of the secret, it should work. The functionality was provided in https://github.com/operator-framework/operator-lifecycle-manager/pull/1878. 

We should consider as follow-up work to validate the spec of the catalog source more closely by setting `preserveUnknownfields: false` so that this catalog would not be applied to the cluster successfully. 

Furthermore, we definitely need to work on docs related to this specific topic as it is a frequent source of confusion. Going to open an issue on the olm-docs repo to track some documentation work related to this: https://github.com/operator-framework/olm-docs/issues/145

**Comment by apurvabhandari** [comment]
`imagePullSecrets` is used to pull image from my private Docker repository and to pull that image this is required.
