### ISSUE TITLE
Why `Subscription` and `InstallPlan` have different approval method?

### ISSUE THREAD

**Issue by 0xff-dev** [operator-framework/operator-lifecycle-manager#2325]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question
Deploy the first operator by manual upgrade. Next, deploy the second operator in an automatic upgrade mode. These operators are in the same namespace. I found that the installplan of the second operator is a manual upgrade, and the field `clusterServiceVersionNames` has multiple values. `When the installplan of the second operator agrees to upgrade, both operators are installed at the same time`

**What did you expect to see?**
One installPlan is only associated with one subscription

**What did you see instead? Under which circumstances?**
Under the same namespace, if there is a subscription that is manually upgraded, no matter what upgrade method is used for the subsequent subscription, the installplan associated with it is manually upgraded

**Environment**
* operator-lifecycle-manager version:
1.17.0

* Kubernetes version information:
1.20

  

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by kevinrizza** [comment]
This is because `InstallPlans` are scoped to all of the operator subscriptions in a given namespace. An installplan aggregates all of the updates that OLM has recognized to be available at one time, and creates a single update plan for all of them. This is due to the way that OLM determines what dependencies are available (largely an artifact of the dependency resolution limitations that OLM had before we implemented a SAT solver in the new resolver).

In the future, we are building a set of new APIs that will not be scoped in this way.
