### ISSUE TITLE
Use cases of csv version skipping

### ISSUE THREAD

**Issue by mateuszstompor** [operator-framework/operator-lifecycle-manager#2465]
## Type of question
Best practices

## Question

**What did you do?**
I develop an operator and have a question about the upgrade process. On one of your documentation [page](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/how-to-update-operators.md) I found that the preferred way of upgrading the operator is to follow each intermediate version during the upgrade (if such exist) when I want to end up having the latest one. Skipping a version is described as a way of avoiding a faulty version. At least I have such an impression after reading the article. Can I use this mechanism just to skip these intermediate steps and upgrade to the latest version right away? In my case there are no faulty versions. Machines where my component is deployed are not connected to the Internet. The less images I need to provide the better it is for me. If I don't skip intermediate versions I need to push all images for intermediate version to the image stream only to allow olm to proceed with upgrade to a newer version

**What did you expect to see?**
Advise from the dev team

**Environment**
* operator-lifecycle-manager version:
OLM version: 0.16.1
git commit: bf72c5d00150acd951894f256cf2e65749326213

* Kubernetes version information:
Openshift, `oc version` output
```
Client Version: 4.6.32
Server Version: 4.6.32
Kubernetes Version: v1.19.0+d670f74
```

* Kubernetes cluster kind: 
3 master + 5 worker nodes

**Comment by cdjohnson** [comment]
Yes.  You can use `skips` or `olm.skipRange` with or without `replaces` to allow the initial install or subsequent upgrades to provision to the head of the channel.

When used WITH `replaces`, the old versions remain in the graph and can be installed using the `startingCSV` setting in a manual subscription.

When used WITHOUT `replaces`, the channel only has the head node.

All of our products (IBM Cloud Paks) currently use this exact approach:  We use `replaces` + `olm.skipRange` within a channel and we use `olm.skipRange` at the origin of each channel.  However, we're likely to move to a hybrid where we don't require `replaces` at all since we haven't found much value in using the `startingCSV` function.

This page was recently updated and may help you more:
https://olm.operatorframework.io/docs/concepts/olm-architecture/operator-catalog/creating-an-update-graph/
