### ISSUE TITLE
Limited RBAC auth request

### ISSUE THREAD

**Issue by weilaaa** [operator-framework/operator-lifecycle-manager#2881]
Do we really need this all permission Items? Seems be better to use limited rbac auth.
https://github.com/operator-framework/operator-lifecycle-manager/blob/91e5d90b3ea330c681656af7d0dc160ecb535876/deploy/chart/templates/0000_50_olm_01-olm-operator.serviceaccount.yaml#L1-L10

**Comment by kevinrizza** [comment]
@weilaaa At it's heart, OLM is a package manager. In order to facilitate installing arbitrary content from any package, OLM requires cluster admin privileges to create arbitrary namespace and cluster scoped resources. Further, even if we did limit the permissions here, OLM creates arbitrary rbac in any scope based on the requirements of whatever package it is installing. You should make sure that whatever package you are installing with OLM is trusted, because those permissions are trivial to escalate -- an operator could request rbac write permission for itself in every namespace it is installed in or at the cluster scope.

That is intentional, by design, and the expectation when using OLM (or helm, or any other arbitrary package manager) is that you either get your catalog from a trusted source or that you ensure that an individual operator that you are installing on a cluster is trusted and only asks for the specific permissions that it needs.

**Comment by weilaaa** [comment]
Yes, it makes sense. I think OLM is just like helm in permissions requirements.
