### ISSUE TITLE
CSV support for ClusterRoles

### ISSUE THREAD

**Issue by darkowlzz** [operator-framework/operator-lifecycle-manager#473]
`StrategyDeploymentPermissions` in CSV `spec.install.spec.permissions` supports specifying rules for RBAC `Roles` only, as per https://github.com/operator-framework/operator-lifecycle-manager/blob/master/pkg/controller/install/deployment.go#L78-L80 . 

Is there a way to add ClusterRoles? I've an operator that needs access to node, persistentvolumeclaim and storageclass, which are cluster level access.

While deploying without OLM, for RBAC permissions, I create a ClusterRole and ClusterRoleBinding, and bind the ClusterRole to the ServiceAccount of my operator.

If this support can be added in the future, I can try implementing it and create a PR.

**Comment by ecordell** [comment]
Hi @darkowlzz, support for creating ClusterRoles is coming very soon (~1wk).

**Comment by ecordell** [comment]
See #477 for progress here

**Comment by ecordell** [comment]
Forgot to come back and update this - ClusterRole support is in via the `clusterPermissions` block on the CSV.

**Comment by wongma7** [comment]
this isn't working for me, any tips to debug? Added clusterPermissions to my csv, the field gets validated, but no clusterRoles nor clusterRoleBindings get created and installation proceeds then fails since the permissions aren't there. olm logs show nothing interesting: I tried grepping for this line https://github.com/operator-framework/operator-lifecycle-manager/blob/f597b7b26f1acb2298d0265daa86e3ca2a0755a1/pkg/controller/operators/olm/requirements.go#L75 but found nothing

**Comment by njhale** [comment]
@wongma7 Are you installing your CSV via `InstallPlan` or by manually creating it?

**Comment by wongma7** [comment]
@njhale I'm manually creating it. So if I am understanding correctly, the InstallPlan would tell the Catalog Operator to create the clusterrole and clusterrolebinding the same way it can tell the Catalog Operator to create a CRD? will the clusterrole and clsuterrolebinding have a deterministic name so that i can make them `required` in my CSV?
