### ISSUE TITLE
Latest console image is broken

### ISSUE THREAD

**Issue by rhuss** [operator-framework/operator-lifecycle-manager#540]
Setup: Minikube, Kubernetes 1.11.4, make run_local, ./scripts/run_console_local.sh:

![image](https://user-images.githubusercontent.com/99080/47561599-0cb06a80-d91c-11e8-8754-a4b734ee9a02.png)

when changing from `latest` to `quay.io/openshift/origin-console:v3.11` then it works again.

Also it looks like that latest points to a v4.0 version so maybe it would be a good idea to pin the tag in `run_console_local/sh` ?

**Comment by ecordell** [comment]
`run_console_local` is really for developing OLM itself, and we prefer to run the latest console to find any issues early

We've greatly improved the CI between OLM and Console since this issue was opened, I believe that will catch most issues like this in the future (and any that don't will re-appear as github issues, I assume 😄)
