### ISSUE TITLE
Docs: Document upgrade behavior (current version must succeed before upgrading to the next version)

### ISSUE THREAD

**Issue by mhrivnak** [operator-framework/operator-lifecycle-manager#879]
### Problem
Many operators perform upgrades on their operands, and/or do other actions, immediately after themselves being upgraded. It can be important for an operator to not be upgraded while it is still in the middle of finishing a previous upgrade.

For example:
* operator gets upgraded from 1.0 to 1.1
* operator starts upgrading its operands
* operator is interrupted and upgraded to 1.2
* Can/must 1.2 finish the upgrade from 1.0?

It would be better for OLM to wait for the 1.1-related upgrade activity to complete before upgrading to 1.2.

### Possible Solution
OLM Could wait for an operator's readiness probe to be `true` before upgrading it. That lines up with the spirit of the readiness probe; it allows a container to do some work at startup before it is "ready" to serve its normal function. When it is done with that work, it communicates that it is ready through the probe.

The best-known example of using a readiness probe in this manner is the [Service controller](https://github.com/kubernetes/kubernetes/blob/v1.13.6/pkg/controller/service/service_controller.go#L613-L618).

**Comment by ecordell** [comment]
Hi @mhrivnak , thanks for the RFE!

Your proposed solution:
>OLM Could wait for an operator's readiness probe to be true before upgrading it.

is actually how OLM performs upgrades today and is the way we suggest you gate important migrations between versions. OLM waits for a CSV to enter the "Succeeded" phase before upgrading (which only occurs when the deployment is marked as ready)

So this begs me to ask: are you seeing behavior that doesn't align with that? If so - that's a bug we should look into.

One idea we've discussed would be an additional layer on top of the standard readiness probes for deployments. The idea would be that an operator could register a set of "upgrade probes" that must succeed in order to consider the current version installed.

**Comment by mhrivnak** [comment]
> is actually how OLM performs upgrades today ... So this begs me to ask: are you seeing behavior that doesn't align with that?

That's great! I have not tested the behavior. I just couldn't find any mention of it in docs, nor could I find the feature in code (didn't do an exhaustive search, but tried some keywords). I asked about it in slack, and @njhale and @alecmerdler weren't aware of it existing either.

It would be helpful to document this somewhere fairly prominent so that operator authors know they can take advantage of it.

**Comment by ecordell** [comment]
> It would be helpful to document this somewhere fairly prominent so that operator authors know they can take advantage of it.

Absolutely, we need to document this better. Changing the issue to a docs request.

**Comment by ecordell** [comment]
This doc outlines how upgrades are held until the operator is ready: https://olm.operatorframework.io/docs/advanced-tasks/communicating-operator-conditions-to-olm/
