### ISSUE TITLE
Installing cluster wide operator into a dedicated namespace

### ISSUE THREAD

**Issue by ctron** [operator-framework/operator-lifecycle-manager#927]
Environment: OpenShift 4.1

We do have an operator, which has set `AllNamespaces: true`, as it contains an API service extension, and needs to run cluster wide. By default, when you install the operator via the Web UI, that operator will always end up in the namespace `openshift-operators`. It seems there is no way to confine this into a dedicated namespace.

The problem with that is, that all the additional resources and deployment the operator creates, will be in the same namespace, cluttering up that "general purpose" operators namespace quite a lot.

So I would be looking for a way to install a cluster wide operator into a namespace I can select.

**Comment by jarrpa** [comment]
I'll jump on to this Issue and take it one step further: I'd like to be able to hardcode a default namespace name that will be created if it doesn't exist. So, for example, I'd like to have an OLM operator that by default would want to get installed in the `mynamespace`  namespace, with the option to change that value to something else. Then, if a namespace with the name doesn't exist, it would get created. It should then be left open to the operator to further modify the target namespace (e.g. with labels) if desired.

**Comment by dmesser** [comment]
@ctron this is a functionality of the OpenShift Console, not OLM. But see below.

@jarrpa we are looking into this for the next version of OLM. The ability to express a desired target namespace implies that you must make a decision on the desired OperatorGroup in that namespace, too.

**Comment by tamireran** [comment]
> @ctron this is a functionality of the OpenShift Console, not OLM. But see below.
> 
> @jarrpa we are looking into this for the next version of OLM. The ability to express a desired target namespace implies that you must make a decision on the desired OperatorGroup in that namespace, too.

@dmesser  Any updates on this one

**Comment by awgreene** [comment]
Thanks for your patience everyone. This project was recently submitted to the CNCF organization and this issue seems to have been created prior to the submission. The OpenShift distribution of OLM can now be found [here](https://github.com/openshift/operator-framework-olm).

Since this issue was reported against the OpenShift distribution of the project, I'm going to describe how to address this concern in that environment. Before doing so, I'd like to make it clear that OLM will not force users to install an operator in a specific namespace as we believe that cluster admins should have a high level of control regarding what and where things are running on their cluster. However, when installing an operator through the OpenShift console UI, if the CSV includes the [suggested namespace annotation on the csv](https://docs.openshift.com/container-platform/4.6/operators/operator_sdk/osdk-generating-csvs.html#osdk-suggested-namespace_osdk-generating-csvs) users will be informed that the operator should be installed in a specific namespace. The user can then make an informed decision and have the UI create the suggested namespace and install the operator within.
